micronaut.application.name=micronaut-json-relational-duality-views
micronaut.router.static-resources.default.mapping=/**
micronaut.router.static-resources.default.paths=classpath:public

datasources.default.db-type=oracle
datasources.default.dialect=ORACLE
datasources.default.driver-class-name=oracle.jdbc.OracleDriver
datasources.default.connection-factory-class-name=oracle.jdbc.pool.OracleDataSource
datasources.default.url=${DB_URL}
datasources.default.username=${DB_USERNAME}
datasources.default.password=${DB_PASSWORD:}
datasources.default.connection-pool-name=micronaut-json-duality-views
datasources.default.initial-pool-size=1
datasources.default.min-pool-size=1
datasources.default.max-pool-size=5
datasources.default.validate-connection-on-borrow=true
datasources.default.sqlfor-validate-connection=select 1 from dual
datasources.default.enable-oracle-client-info=true

oracle.ucp.destroyOnReload=true
